version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: supermarket-pos-db
    environment:
      POSTGRES_DB: supermarket_pos
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
