server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supermarket_pos
    username: pos_user
    password: pos_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "CHANGE_ME_SUPERMARKET_POS_SECRET_KEY_256_BITS_MIN"
    expirationMinutes: 720

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui
